[workspace]
members = ["payjoin", "payjoin-cli", "payjoin-directory", "payjoin-test-utils", "payjoin-ffi"]
resolver = "2"

[patch.crates-io.payjoin]
path = "payjoin"

[patch.crates-io.payjoin-directory]
path = "payjoin-directory"
