[package]
name = "payjoin-cli"
version = "0.0.1"
authors = ["Dan Gould <d@ngould.dev>", "Martin Habovstiak <martin.habovstiak@gmail.com>"]
repository = "https://github.com/payjoin/rust-payjoin"
readme = "README.md"
edition = "2021"
resolver = "2"

[[bin]]
name = "payjoin-cli"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
native-tls-vendored = ["reqwest/native-tls-vendored"]
local-https = ["rcgen", "rouille/ssl"]

[dependencies]
anyhow = "1.0.70"
bip21 = "0.3.1"
bitcoincore-rpc = "0.17.0"
clap = "4.1.4"
config = "0.13.3"
env_logger = "0.9.0"
log = "0.4.7"
payjoin = { path = "../payjoin", features = ["send", "receive", "base64"] }
reqwest = { version = "0.11.4", features = ["blocking"] }
rcgen = { version = "0.11.1", optional = true }
rouille = "3.6.2"
serde = { version = "1.0.160", features = ["derive"] }

[dev-dependencies]
bitcoind = { version = "0.31.1", features = ["0_21_2"] }
tokio = { version = "1.12.0", features = ["full"] }