name: Test and Build

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.63.0 # MSRV
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Fixes for MSRV
        if: matrix.rust == '1.63.0'
        run: |
          cargo update
          cargo update -p cc --precise 1.0.105
          cargo update -p clap_lex --precise 0.3.0
          cargo update -p regex --precise 1.9.6
          cargo update -p reqwest --precise 0.12.4
          cargo update -p time@0.3.36 --precise 0.3.20
          cargo update -p tokio --precise 1.38.1
          cargo update -p url --precise 2.5.0
          cargo update -p which --precise 4.4.0
      - name: Run tests
        run: bash contrib/test.sh

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
      - name: fmt check
        run: cargo fmt --all -- --check
